version: "3"

services:
    ##############################
    ### SETUP SERVER CONTAINER ###
    ##############################
    server:
        # tell docker what file to build the server from
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        # ports to expose
        expose:
            - 4000
        # environment variables
        environment: 
            - MONGO_URI=mongodb://db:27017/db
            - PORT=4000
            - NODE_ENV=development
        # port mapping
        ports:
            - 4000:4000
        # volumes to mount
        volumes:
            - ./server/src:/app/server/src
        # Run command
        # nodemon for hot reloading (-L flag required for polling  in Docker)
        command: nodemon -L src/index.js
        # connect to other containers:
        links:
            - db
        # restart action
        restart: always
    ##############################
    ### SETUP CLIENT CONTAINER ###
    ##############################
    client:
        build:
            context: ./client
            dockerfile: Dockerfile-dev
        environment:
            - REACT_APP_PORT=3000
            - CHOKIDAR_USEPOLLING=true
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/app/client/src
            - ./client/public:/app/client/public
        links:
            - server
        command: npm run start
        restart: always
    ##########################
    ### SETUP DB CONTAINER ###
    ##########################
    db:
        image: mongo
        ports:
            - 27017:27017
        restart: always
