# server/Dockerfile-dev

# Install node image in container
FROM node

# Install nodemon for hot reloading
RUN npm install -g nodemon

# Create and set the working directory
RUN mkdir -p /app/server
WORKDIR /app/server

# Copy the dependencies
COPY package.json /app/server/
copy yarn.lock /app/server/

# Install the dependencies
RUN yarn install

# Command to run
CMD [ "nodemon", "index.js" ]